/**
 * Bundle the sandbox-runtime.ts into a self-contained IIFE string
 * 
 * This script:
 * 1. Uses esbuild to bundle sandbox-runtime.ts with all dependencies inlined
 * 2. Outputs the result as a TypeScript file exporting the code as a string
 * 3. The bundled code can then be run in vm or isolated-vm contexts
 */

import { build } from 'esbuild';
import { writeFileSync } from 'fs';
import { fileURLToPath } from 'url';
import { dirname, join } from 'path';

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);

async function bundleSandbox() {
  const entryPoint = join(__dirname, '../src/runner/sandbox-runtime.ts');
  const outputPath = join(__dirname, '../src/runner/sandbox-runtime.bundle.ts');

  try {
    // Bundle the sandbox runtime into an IIFE
    const result = await build({
      entryPoints: [entryPoint],
      bundle: true,
      format: 'iife',
      write: false,
      minify: false, // Keep readable for debugging
      target: 'es2020',
      platform: 'neutral', // Works in both Node.js and browser-like environments
      // Don't define external - we want to bundle everything inline
      treeShaking: true,
    });

    if (result.outputFiles && result.outputFiles.length > 0) {
      const bundledCode = result.outputFiles[0].text;
      
      // Generate the output TypeScript file
      const outputContent = `/**
 * Auto-generated sandbox runtime bundle
 * 
 * DO NOT EDIT - This file is generated by scripts/bundle-sandbox.ts
 * 
 * Run 'pnpm run bundle-sandbox' to regenerate
 */

/**
 * The bundled sandbox runtime code as a string.
 * This code runs inside the vm or isolated-vm context.
 * 
 * Before running, the host must set _playerId global:
 * \`\`\`
 * context.global._playerId = 'player1';
 * \`\`\`
 */
export const sandboxRuntimeCode = ${JSON.stringify(bundledCode)};
`;

      writeFileSync(outputPath, outputContent, 'utf-8');
      console.log(`✓ Bundled sandbox runtime to ${outputPath}`);
      console.log(`  Size: ${(bundledCode.length / 1024).toFixed(1)} KB`);
    } else {
      throw new Error('No output files generated');
    }
  } catch (error) {
    console.error('Failed to bundle sandbox runtime:', error);
    process.exit(1);
  }
}

bundleSandbox();
